// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: order.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OrderRPCService_CreateOrder_FullMethodName = "/rpc.OrderRPCService/CreateOrder"
	OrderRPCService_GetOrder_FullMethodName    = "/rpc.OrderRPCService/GetOrder"
)

// OrderRPCServiceClient is the client API for OrderRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderRPCServiceClient interface {
	CreateOrder(ctx context.Context, in *NewOrderMessage, opts ...grpc.CallOption) (*OrderMessage, error)
	GetOrder(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*OrderMessage, error)
}

type orderRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderRPCServiceClient(cc grpc.ClientConnInterface) OrderRPCServiceClient {
	return &orderRPCServiceClient{cc}
}

func (c *orderRPCServiceClient) CreateOrder(ctx context.Context, in *NewOrderMessage, opts ...grpc.CallOption) (*OrderMessage, error) {
	out := new(OrderMessage)
	err := c.cc.Invoke(ctx, OrderRPCService_CreateOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRPCServiceClient) GetOrder(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*OrderMessage, error) {
	out := new(OrderMessage)
	err := c.cc.Invoke(ctx, OrderRPCService_GetOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderRPCServiceServer is the server API for OrderRPCService service.
// All implementations must embed UnimplementedOrderRPCServiceServer
// for forward compatibility
type OrderRPCServiceServer interface {
	CreateOrder(context.Context, *NewOrderMessage) (*OrderMessage, error)
	GetOrder(context.Context, *IdMessage) (*OrderMessage, error)
	mustEmbedUnimplementedOrderRPCServiceServer()
}

// UnimplementedOrderRPCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderRPCServiceServer struct {
}

func (UnimplementedOrderRPCServiceServer) CreateOrder(context.Context, *NewOrderMessage) (*OrderMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderRPCServiceServer) GetOrder(context.Context, *IdMessage) (*OrderMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderRPCServiceServer) mustEmbedUnimplementedOrderRPCServiceServer() {}

// UnsafeOrderRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderRPCServiceServer will
// result in compilation errors.
type UnsafeOrderRPCServiceServer interface {
	mustEmbedUnimplementedOrderRPCServiceServer()
}

func RegisterOrderRPCServiceServer(s grpc.ServiceRegistrar, srv OrderRPCServiceServer) {
	s.RegisterService(&OrderRPCService_ServiceDesc, srv)
}

func _OrderRPCService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewOrderMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRPCServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRPCService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRPCServiceServer).CreateOrder(ctx, req.(*NewOrderMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRPCService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRPCServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRPCService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRPCServiceServer).GetOrder(ctx, req.(*IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderRPCService_ServiceDesc is the grpc.ServiceDesc for OrderRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.OrderRPCService",
	HandlerType: (*OrderRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderRPCService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderRPCService_GetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
