name: "Test"
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Checkout repository"

      - name: "Start Docker containers"
        run: RELEASE_MODE=prod docker compose up -d

      - uses: actions/setup-go@v5
        name: "Setup golang"
        with:
          go-version: "1.23.3"

      - name: "Run user unit tests"
        run: make user_test

      - name: "Run order unit tests"
        run: make order_test

      - name: "Run e2e tests"
        run: make e2e_test
